spring:
  application:
    name: boot-rocketmq-demo
  logging:
   level: info
management:
  #server:
  #  port: 9719
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
     show-details: ALWAYS
rocketmq:
  name-server: localhost:9876
  producer:
    group: ${spring.application.name}
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-failed: 3
    retry-next-server: false
    retry-times-when-send-async-failed: 3

